name = "we-dev-pages"

# Cloudflare Pages build settings (Wrangler-managed)
pages_build_output_dir = "apps/we-dev-client/dist"
build_command = "cd apps/we-dev-client && pnpm i --ignore-scripts && pnpm run builds"

